Repository onesunny2/Sgrrl_Cakey, pull requests merged in 2024-11, with the labels that each got.

#2 [chore] #1 컬러에셋 초기 세팅
  Cakey/Assets.xcassets/CakeyColor/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Main/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Main/cakeyOrange1.colorset/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Main/cakeyOrange2.colorset/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Main/cakeyYellow1.colorset/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Main/cakeyYellow2.colorset/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Sub/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Sub/pickerBlue.colorset/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Sub/pickerPink.colorset/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Sub/pickerPurple.colorset/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Sub/pickerWhite.colorset/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Sub/pickerYellow.colorset/Contents.json
Labels: 🧹chore

#4 [Feat] #3 CakeyModel 설계
  Cakey/Model/CakeyModel.swift
Labels: ✨feat

#8 [Feat] #6 Cakey HomeView UI 초안 구현
  Cakey/Assets.xcassets/CakeyImage/Contents.json
  Cakey/Assets.xcassets/CakeyImage/HomeView/Contents.json
  Cakey/Assets.xcassets/CakeyImage/HomeView/cakeBG.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/HomeView/cakeBG.imageset/cakeBG@2x.png
  Cakey/Assets.xcassets/CakeyImage/HomeView/cakeBG.imageset/cakeBG@3x.png
  Cakey/CakeyApp.swift
  Cakey/Views/Home/HomeView.swift
Labels: ✨feat

#10 [Chore] #9 ChangeCustomFont,ColorAsset
  Cakey/Assets.xcassets/CakeyColor/Main/cakeyOrange3.colorset/Contents.json
  Cakey/Extensions/Font+Extensions.swift
Labels: 🧹chore

#12 [Chore] #11 HomeView UI 수정
  Cakey/ContentView.swift
  Cakey/Views/Home/HomeView.swift
Labels: 🧹chore

#17 [chore] #16 홈뷰 cake 이미지 교체
  Cakey/Assets.xcassets/CakeyImage/HomeView/cakeBG.imageset/cakeBG@2x.png
  Cakey/Assets.xcassets/CakeyImage/HomeView/cakeBG.imageset/cakeBG@3x.png
Labels: 🧹chore

#18 [Feat] #15 CakeColorView UI 구현
  Cakey/Views/CakeyOrderForm/CakeColorView.swift
  Cakey/Views/CakeyOrderForm/CakeImageView.swift
  Cakey/Views/Components/ColorPickerCell.swift
  Cakey/Views/Components/NextButtonCell.swift
  Cakey/Views/Components/NoticeCelll.swift
  Cakey/Views/Components/ProgressBarCell.swift
  Cakey/Views/Home/HomeView.swift
Labels: ✨feat

#22 [Chore] #21 커스텀 폰트 수정, new 컬러에셋 추가
  Cakey/Assets.xcassets/CakeyColor/Sub/pickerBlack.colorset/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Sub/textFieldBlack.colorset/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Sub/textFieldGray.colorset/Contents.json
  Cakey/Assets.xcassets/CakeyColor/Sub/textFieldWhite.colorset/Contents.json
  Cakey/Extensions/Font+Extensions.swift
Labels: 🧹chore

#24 [Chore] #23 CakeColorView 컬러피커 투명도 조절 가능하도록 수정
  Cakey/Views/Components/ColorPickerCell.swift
Labels: 🧹chore

#29 [Feat] #28 CakeImageView 안내문구, SKIP버튼, 다음버튼 추가(기능은 미구현)
  Cakey/Views/CakeyOrderForm/CakeDecorationView.swift
  Cakey/Views/CakeyOrderForm/CakeImageView.swift
  Cakey/Views/Components/DecoCarouselCell.swift
  Cakey/Views/Components/textFieldCell.swift
  Cakey/Views/Home/HomeView.swift
Labels: ✨feat

#31 [Feat] #30 커스텀 네비게이션 back 버튼, 완료 버튼, 안내 문구, 프로그래스바, 3D케이크 자리 마련 완료
  Cakey/Assets.xcassets/CakeyImage/examples/Contents.json
  Cakey/Assets.xcassets/CakeyImage/examples/zzamong.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/examples/zzamong.imageset/짜몽1 1.jpeg
  Cakey/Assets.xcassets/CakeyImage/examples/zzamong.imageset/짜몽1 2.jpeg
  Cakey/Views/CakeyOrderForm/CakeDecorationView.swift
  Cakey/Views/CakeyOrderForm/CakeLetteringView.swift
  Cakey/Views/Components/DecoActionCell.swift
  Cakey/Views/Components/DecoImageCell.swift
  Cakey/Views/Home/HomeView.swift
Labels: ✨feat

#34 [Fix] #33 ColorPickerCell 코드 수정
  Cakey/Views/CakeyOrderForm/CakeColorView.swift
  Cakey/Views/Components/ColorPickerCell.swift
Labels: 🔧fix

#36 [Chore] #35 ImageAsset 파일명 수정해서 재등록
  Cakey/Assets.xcassets/CakeyImage/examples/zzamong.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/examples/zzamong.imageset/zzamong 1.jpeg
  Cakey/Assets.xcassets/CakeyImage/examples/zzamong.imageset/zzamong.jpeg
Labels: 🧹chore

#37 [Feat] #19 Realm 설치 및 manager 생성, 모델 구조 수정 후 viewModel 생성
  Cakey/CakeyApp.swift
  Cakey/ContentView.swift
  Cakey/Model/CakeyModel.swift
  Cakey/Model/CakeyViewModel.swift
  Cakey/Model/Manager/RealmManager.swift
  Cakey/Model/Protocol/Persistable.swift
  CakeyTests/CakeyTests.swift
Labels: ✨feat

#39 [Fix] #38 DS_Store 삭제, SPM Realm 재설치
  .DS_Store
  Cakey.xcodeproj/project.pbxproj
  Cakey.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Cakey.xcodeproj/project.xcworkspace/xcuserdata/leewonsun.xcuserdatad/UserInterfaceState.xcuserstate
  Cakey/.DS_Store
  Cakey/CakeScene/.DS_Store
  Cakey/CakeScene/.swiftpm/xcode/xcuserdata/leewonsun.xcuserdatad/xcschemes/xcschememanagement.plist
  Cakey/CakeScene/Sources/.DS_Store
  Cakey/CakeScene/Sources/CakeScene/.DS_Store
Labels: 🔧fix

#41 [Docs] ContentView 삭제
  Cakey.xcodeproj/project.pbxproj
  Cakey.xcodeproj/project.xcworkspace/xcuserdata/leewonsun.xcuserdatad/UserInterfaceState.xcuserstate
  Cakey/CakeyApp.swift
  Cakey/ContentView.swift
Labels: 📄docs

#43 [Chore] #42 자잘한 디자인 수정
  Cakey/Views/CakeyOrderForm/CakeDecorationView.swift
  Cakey/Views/Components/DecoImageCell.swift
  Cakey/Views/Components/ProgressBarCell.swift
Labels: 🧹chore

#44 [Feat] #32 CakeLetteringViewUI
  Cakey.xcodeproj/project.xcworkspace/xcuserdata/leewonsun.xcuserdatad/UserInterfaceState.xcuserstate
  Cakey/Extensions/Font+Extensions.swift
  Cakey/Extensions/View+Extensions.swift
  Cakey/Views/CakeyOrderForm/CakeColorView.swift
  Cakey/Views/CakeyOrderForm/CakeDecorationView.swift
  Cakey/Views/CakeyOrderForm/CakeImageView.swift
  Cakey/Views/CakeyOrderForm/CakeLetteringView.swift
  Cakey/Views/CakeyOrderForm/CakeOrderformView.swift
  Cakey/Views/Components/CakeColorPickerCell.swift
  Cakey/Views/Components/LetteringColorPickerCell.swift
  Cakey/Views/Components/TextEditorCell.swift
  Cakey/Views/Components/TextFieldCell.swift
  Cakey/Views/Home/HomeView.swift
Labels: ✨feat

#46 [Feat] #45 OrderFormCompleteView UI
  Cakey.xcodeproj/project.xcworkspace/xcuserdata/leewonsun.xcuserdatad/UserInterfaceState.xcuserstate
  Cakey/Views/CakeyOrderForm/CakeColorView.swift
  Cakey/Views/CakeyOrderForm/CakeDecorationView.swift
  Cakey/Views/CakeyOrderForm/CakeImageView.swift
  Cakey/Views/CakeyOrderForm/CakeLetteringView.swift
  Cakey/Views/CakeyOrderForm/CakeOrderformView.swift
  Cakey/Views/Components/NextButtonCell.swift
  Cakey/Views/Home/HomeView.swift
Labels: ✨feat

#50 [Feat] #49 SaveButtonActionSheet 및 스크린샷 저장 구현
  Cakey.xcodeproj/project.pbxproj
  Cakey.xcodeproj/project.xcworkspace/xcuserdata/leewonsun.xcuserdatad/UserInterfaceState.xcuserstate
  Cakey/Extensions/UIView+Extensions.swift
  Cakey/Extensions/View+Extensions.swift
  Cakey/Views/CakeyOrderForm/CakeOrderformView.swift
  Cakey/Views/OrderFormArchieve/ArchieveDetailView.swift
Labels: ✨feat

#53 [Chore] #51 UX라이팅 수정
  Cakey.xcodeproj/project.xcworkspace/xcuserdata/leewonsun.xcuserdatad/UserInterfaceState.xcuserstate
  Cakey/Views/Components/TextEditorCell.swift
Labels: 🧹chore

#54 [Feat] #52 데이터 CRUD 연결
  Cakey.xcodeproj/project.xcworkspace/xcuserdata/leewonsun.xcuserdatad/UserInterfaceState.xcuserstate
  Cakey/Extensions/Color+Extensions.swift
  Cakey/Model/ArchieveViewModel.swift
  Cakey/Model/CakeyModel.swift
  Cakey/Model/CakeyViewModel.swift
  Cakey/Model/Destination.swift
  Cakey/Model/Manager/PhotosPickerManager.swift
  Cakey/Views/CakeyOrderForm/CakeColorView.swift
  Cakey/Views/CakeyOrderForm/CakeDecorationView.swift
  Cakey/Views/CakeyOrderForm/CakeImageView.swift
  Cakey/Views/CakeyOrderForm/CakeLetteringView.swift
  Cakey/Views/CakeyOrderForm/CakeOrderformView.swift
  Cakey/Views/Components/ArchieveCell.swift
  Cakey/Views/Components/DecoCarouselCell.swift
  Cakey/Views/Components/DecoImageCell.swift
  Cakey/Views/Home/HomeView.swift
  Cakey/Views/OrderFormArchieve/ArchieveDetailView.swift
  Cakey/Views/OrderFormArchieve/ArchieveView.swift
Labels: ✨feat

#57 [Release] #56 앱아이콘 추가, 빌드 세팅
  Cakey.xcodeproj/project.pbxproj
  Cakey.xcodeproj/project.xcworkspace/xcuserdata/leewonsun.xcuserdatad/UserInterfaceState.xcuserstate
  Cakey/Assets.xcassets/AppIcon.appiconset/CakeyIcon.png
  Cakey/Assets.xcassets/AppIcon.appiconset/Contents.json
Labels: 🧹chore

#58 [Chore] #55 CakeyModel에 3D이미지 요소 추가
  Cakey.xcodeproj/project.xcworkspace/xcuserdata/leewonsun.xcuserdatad/UserInterfaceState.xcuserstate
  Cakey/Model/CakeyModel.swift
Labels: 🧹chore

#62 [Feat] #59 CakeImageView 기능 구현
  .gitignore
  Cakey.xcodeproj/project.xcworkspace/xcuserdata/leewonsun.xcuserdatad/UserInterfaceState.xcuserstate
  Cakey.xcodeproj/xcuserdata/leewonsun.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Cakey/Model/CakeyModel.swift
  Cakey/Model/Manager/ImageDownsample.swift
  Cakey/Model/Manager/ImagePicker.swift
  Cakey/Model/Manager/PhotosPickerManager.swift
  Cakey/Views/CakeyOrderForm/CakeColorView.swift
  Cakey/Views/CakeyOrderForm/CakeImageView.swift
  Cakey/Views/CakeyOrderForm/CakeLetteringView.swift
  Cakey/Views/Components/DecoCarouselCell.swift
  Cakey/Views/Components/DecoImageCell.swift
  Cakey/Views/Components/NextButtonCell.swift
  Cakey/Views/Components/TextFieldCell.swift
Labels: ✨feat

#64 [Chore] #63 ArchieveViewModel 내부 Read 함수에 완료 유무 변수로 조건 추가
  Cakey/Model/ArchieveViewModel.swift
Labels: 🧹chore

#66 [Feat] #65 CakeLetteringView 다음 버튼에 isComplete를 true로 저장하도록 구현
  Cakey/Model/ArchieveViewModel.swift
  Cakey/Views/CakeyOrderForm/CakeLetteringView.swift
  Cakey/Views/OrderFormArchieve/ArchieveView.swift
Labels: ✨feat

#68 [Feat] #67 CakeOrderformView에 realm Update 시키기
  Cakey/Model/ArchieveViewModel.swift
  Cakey/Views/CakeyOrderForm/CakeOrderformView.swift
Labels: ✨feat

#69 [Feat]#20 3D 색상 선택 및 데코 기능 추가
  Cakey/Assets.xcassets/CakeyImage/examples/jpg.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/examples/jpg.imageset/jpg.jpg
  Cakey/Assets.xcassets/CakeyImage/examples/p1.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/examples/p1.imageset/p1.png
  Cakey/Assets.xcassets/CakeyImage/examples/p2.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/examples/p2.imageset/choco.png
  Cakey/Assets.xcassets/CakeyImage/examples/p3.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/examples/p3.imageset/pancakes.png
  Cakey/Assets.xcassets/CakeyImage/examples/p4.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/examples/p4.imageset/snowball.png
  Cakey/Assets.xcassets/CakeyImage/examples/p5.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/examples/p5.imageset/doll.png
  Cakey/Assets.xcassets/CakeyImage/examples/p6.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/examples/p6.imageset/p6.png
  Cakey/Assets.xcassets/CakeyImage/examples/sampleText.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/examples/sampleText.imageset/sampleText.png
  Cakey/CakeScene/.DS_Store
  Cakey/CakeScene/Package.realitycomposerpro/ProjectData/main.json
  Cakey/CakeScene/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Cakey/CakeScene/Package.realitycomposerpro/WorkspaceData/dora.rcuserdata
  Cakey/CakeScene/Sources/CakeScene/CakeScene.rkassets/DefaultAttenuationMap.exr
  Cakey/CakeScene/Sources/CakeScene/CakeScene.rkassets/Ground.usda
  Cakey/CakeScene/Sources/CakeScene/CakeScene.rkassets/Scene.usda
  Cakey/CakeScene/Sources/CakeScene/CakeScene.rkassets/SkyDome.usdz
  Cakey/CakeScene/Sources/CakeScene/CakeScene.rkassets/ring.usdz
  Cakey/CakeScene/Sources/CakeScene/CakeScene.rkassets/textures/color_121212 1.hdr
  Cakey/CakeScene/Sources/CakeScene/CakeScene.rkassets/textures/color_121212.hdr
  Cakey/Views/3D/Cake3DColorView.swift
  Cakey/Views/3D/Cake3DDecoView.swift
  Cakey/Views/3D/Cake3DView.swift
  Cakey/Views/3D/CameraData.swift
  Cakey/Views/3D/DecoViewComponents.swift
  Cakey/Views/3D/TestView.swift
  Cakey/Views/3D/VerticalSlider.swift
  Cakey/Views/CakeyOrderForm/CakeColorView.swift
  Cakey/Views/CakeyOrderForm/CakeDecorationView.swift
  Cakey/Views/Components/DecoActionCell.swift
  Cakey/Views/Components/DecoImageCell.swift
  Cakey/composer/Package.realitycomposerpro/ProjectData/main.json
  Cakey/composer/Package.realitycomposerpro/WorkspaceData/SceneMetadataList.json
  Cakey/composer/Package.realitycomposerpro/WorkspaceData/Settings.rcprojectdata
  Cakey/composer/Package.realitycomposerpro/WorkspaceData/dora.rcuserdata
  Cakey/composer/Package.swift
  Cakey/composer/Sources/composer/composer.rkassets/Scene.usda
  Cakey/composer/Sources/composer/composer.rkassets/holecut.usdz
  Cakey/composer/Sources/composer/composer.rkassets/holecutGreen.usdz
  Cakey/composer/Sources/composer/composer.swift
Labels: ✨feat

#72 [Chore] #71 라미의 머지 코드 업데이트
  Cakey/Views/3D/Cake3DColorView.swift
  Cakey/Views/3D/Cake3DDecoView.swift
  Cakey/Views/3D/DecoViewComponents.swift
  Cakey/Views/CakeyOrderForm/CakeDecorationView.swift
  Cakey/Views/Home/HomeView.swift
  Cakey/composer/.swiftpm/xcode/xcuserdata/leewonsun.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: 🧹chore

#76 [feat] #75 케이크 레터링뷰에서 스킵 클릭 시 다음 화면 넘어가도록 구현
  Cakey.xcodeproj/xcuserdata/leewonsun.xcuserdatad/xcschemes/xcschememanagement.plist
  Cakey/CakeScene/.swiftpm/xcode/xcuserdata/leewonsun.xcuserdatad/xcschemes/xcschememanagement.plist
  Cakey/Views/CakeyOrderForm/CakeLetteringView.swift
  Cakey/composer/.swiftpm/xcode/xcuserdata/leewonsun.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: ✨feat

#78 [Chore] #77 ArchieveDetailView도 탭뷰 삭제 진행
  Cakey/Views/OrderFormArchieve/ArchieveDetailView.swift
Labels: 🧹chore

#80 [Chore] #79 CakeOrderformView 키워드 리스트 UI 구현 방식 수정
  Cakey/Views/CakeyOrderForm/CakeOrderformView.swift
Labels: 🧹chore

#82 [Chore] #81 CakeOrderformView UI 수정
  Cakey/Views/CakeyOrderForm/CakeOrderformView.swift
Labels: 🧹chore

#84 [Feat] #83 CakeImageView 사진 누끼
  Cakey/Model/Manager/ImagePicker.swift
  Cakey/Views/Components/DecoCarouselCell.swift
Labels: ✨feat

#86 [Chore] #85 아무 이미지 선택 안했을 때, 빈 셀들 나오도록 수정
  Cakey/Views/3D/Cake3DDecoView.swift
  Cakey/Views/3D/DecoViewComponents.swift
Labels: 🧹chore

#90 [Feat] #73 CakeOrderformView 케이크만 저장하기 구현 및 모델에 사진 저장하기
  Cakey/Extensions/UIView+Extensions.swift
  Cakey/Views/CakeyOrderForm/CakeOrderformView.swift
  Cakey/Views/Components/ArchieveCell.swift
  Cakey/Views/OrderFormArchieve/ArchieveView.swift
Labels: ✨feat
