Repository onesunny2/Sgrrl_Cakey, pull requests merged in 2024-12, with the labels that each got.

#97 [Feat]#70 3D 에디터 기능 1차 마무리
  Cakey.xcodeproj/project.pbxproj
  Cakey.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
  Cakey.xcodeproj/project.xcworkspace/xcuserdata/dora.xcuserdatad/UserInterfaceState.xcuserstate
  Cakey.xcodeproj/project.xcworkspace/xcuserdata/dora.xcuserdatad/WorkspaceSettings.xcsettings
  Cakey.xcodeproj/xcuserdata/dora.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist
  Cakey/Assets.xcassets/CakeyImage/DecoOnboarding/Contents.json
  Cakey/Assets.xcassets/CakeyImage/DecoOnboarding/DecoCell.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/DecoOnboarding/DecoCell.imageset/DecoCell.png
  Cakey/Assets.xcassets/CakeyImage/DecoOnboarding/DecoSlider.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/DecoOnboarding/DecoSlider.imageset/DecoSlider.png
  Cakey/Assets.xcassets/CakeyImage/DecoOnboarding/selectHighlight.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/DecoOnboarding/selectHighlight.imageset/selectHighlight.png
  Cakey/Extensions/Color+Extensions.swift
  Cakey/Model/CakeyModel.swift
  Cakey/Model/CakeyViewModel.swift
  Cakey/Model/Manager/RealmManager.swift
  Cakey/Views/3D/Cake3DColorView.swift
  Cakey/Views/3D/Cake3DDecoView.swift
  Cakey/Views/3D/Cake3DFinalView.swift
  Cakey/Views/3D/Cake3DLetteringView.swift
  Cakey/Views/3D/CameraData.swift
  Cakey/Views/3D/DecoEntities.swift
  Cakey/Views/3D/DecoOnboardingView.swift
  Cakey/Views/3D/DecoViewComponents.swift
  Cakey/Views/CakeyOrderForm/CakeDecorationView.swift
  Cakey/Views/CakeyOrderForm/CakeLetteringView.swift
  Cakey/Views/CakeyOrderForm/CakeOrderformView.swift
  Cakey/composer/.swiftpm/xcode/xcuserdata/dora.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: ✨feat, 🔧fix, ⚙️refactor

#100 [Feat] #94 저장된 도안 하나도 없을 때 안내 화면 뜨도록 구현
  Cakey.xcodeproj/project.pbxproj
  Cakey.xcodeproj/xcuserdata/leewonsun.xcuserdatad/xcschemes/xcschememanagement.plist
  Cakey/Assets.xcassets/CakeyImage/ArchiveView/Contents.json
  Cakey/Assets.xcassets/CakeyImage/ArchiveView/blankImage.imageset/Contents.json
  Cakey/Assets.xcassets/CakeyImage/ArchiveView/blankImage.imageset/blankImage@2x.png
  Cakey/Assets.xcassets/CakeyImage/ArchiveView/blankImage.imageset/blankImage@3x.png
  Cakey/CakeScene/.swiftpm/xcode/xcuserdata/leewonsun.xcuserdatad/xcschemes/xcschememanagement.plist
  Cakey/Views/OrderFormArchieve/ArchieveView.swift
  Cakey/composer/.swiftpm/xcode/xcuserdata/leewonsun.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: ✨feat

#105 [Chore] #104 앱 아이콘 변경
  Cakey.xcodeproj/xcuserdata/leewonsun.xcuserdatad/xcschemes/xcschememanagement.plist
  Cakey/Assets.xcassets/AppIcon.appiconset/CakeyIcon.png
  Cakey/CakeScene/.swiftpm/xcode/xcuserdata/leewonsun.xcuserdatad/xcschemes/xcschememanagement.plist
  Cakey/composer/.swiftpm/xcode/xcuserdata/leewonsun.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: 🧹chore

#106 [Chore] #88 ArchieveDetailView의 내용 오더폼에 맞춰서 변경, 3DFinalView의 파라미터 vie…
  Cakey.xcodeproj/project.pbxproj
  Cakey/Views/3D/Cake3DFinalView.swift
  Cakey/Views/CakeyOrderForm/CakeOrderformView.swift
  Cakey/Views/OrderFormArchieve/ArchieveDetailView.swift
Labels: 🧹chore
